name: Update Podspec on Release

on:
  release:
    types:
      - published

jobs:
  generate_podspec:
    runs-on: ubuntu-latest
    env:
      SDK_NAME: TapOnPhone-iOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby for Podspec generation
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Get release version and name
        id: get_release_info
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          echo "Release Name: $RELEASE_NAME"
          echo "Release Version: $RELEASE_VERSION"

          if [[ "$RELEASE_NAME" =~ TapOnPhoneSDK-iOS ]]; then
            echo "Release matches the pattern."
            echo "MATCHED=true" >> $GITHUB_ENV
          else
            echo "Release does not match the pattern."
            echo "MATCHED=false" >> $GITHUB_ENV
          fi

      - name: Exit if release name doesn't match the pattern
        if: env.MATCHED == 'false'
        run: |
          echo "Release name does not match the expected pattern. Exiting."
          exit 0

      - name: Download the .zip file from the public release
        run: |
          RELEASE_URL="https://github.com/getzoop/zoop-package-public/releases/download/${{ github.event.release.tag_name }}/TapOnPhoneSDK-iOS.zip"
          echo "Downloading .zip from: $RELEASE_URL"
          
          curl -L -o sdk-release.zip $RELEASE_URL
          
          if [[ ! -f sdk-release.zip ]]; then
            echo "Error: .zip file not downloaded successfully."
            exit 1
          fi

      - name: Unzip the .zip file
        run: |
          unzip sdk-release.zip -d sdk-release/
          
          if [[ ! -d sdk-release/TapOnPhoneSDK.xcframework ]]; then
            echo "Error: Expected xcframework file not found in the extracted folder."
            exit 1
          fi

      - name: Create Podspec file
        run: |
          XCFRAMEWORK_ROOT="./sdk-release"
          SDK_VERSION=$RELEASE_VERSION
          
          PODSPEC_CONTENT="
          Pod::Spec.new do |s|
            s.name             = '${SDK_NAME}'
            s.version          = '${{ github.event.release.tag_name }}'
            s.summary          = 'Tap on phone SDK for iOS'
            s.description      = 'Receive payments with iPhone using NFC'
            s.homepage         = 'https://github.com/getzoop/zoop-package-public'
            s.license          = { :type => 'MIT', :file => 'LICENSE' }
            s.author           = { 'Wellington Nascente Hirsch' => 'wellington.hirsch@ifood.com.br' }
            s.source           = { :git => 'https://github.com/getzoop/zoop-package-public.git', :tag => '${{ github.event.release.tag_name }}' }
            s.source_files     = '${XCFRAMEWORK_ROOT}/**/*.h'
            s.public_header_files = '${XCFRAMEWORK_ROOT}/**/*.h'
            s.vendored_frameworks = '${XCFRAMEWORK_ROOT}/TapOnPhoneSDK.xcframework'
            s.requires_arc     = true
            s.pod_target_xcconfig = { 'SWIFT_VERSION' => '5.0' }
            s.frameworks        = 'UIKit'
          end
          "
          echo "$PODSPEC_CONTENT" > "${SDK_NAME}.podspec"
          echo "Podspec file created: ${SDK_NAME}.podspec"

      - name: Create Swift Package file
        run: |
          ROOT="./sdk-release"
          PACKAGE_NAME="${{ github.event.release.name }}"
          PACKAGE_VERSION="${{ github.event.release.tag_name }}"
      
          PACKAGE_CONTENT="
          // swift-tools-version: 5.6
          import PackageDescription
      
          let package = Package(
              name: \"${PACKAGE_NAME}\",
              platforms: [
                  .iOS(.v16_4)
              ],
              products: [
                  .library(
                      name: \"${PACKAGE_NAME}\",
                      targets: [\"TapOnPhoneSDK\"])
              ],
              targets: [
                  .binaryTarget(
                      name: \"TapOnPhoneSDK\",
                      path: \"${ROOT}/TapOnPhoneSDK.xcframework\"
                  )
              ]
          )
          "      
          echo "$PACKAGE_CONTENT" > Package.swift
          echo "Package.swift criado com sucesso:"

      - name: Commit and push Podspec file to specific branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          BRANCH_NAME="${{ github.event.release.name }}/${{ github.event.release.tag_name }}"
          echo "Branch: $BRANCH_NAME"
          
          git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
          
          git add --all
          git commit -m "Update Podspec for release ${SDK_VERSION}"
          
          git push origin "$BRANCH_NAME"
